global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'youtube-proxy-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - /etc/prometheus/alerting-rules.yml

scrape_configs:
  - job_name: 'youtube_proxy'
    static_configs:
      - targets: ['app:9000']
    scrape_interval: 10s
    scrape_timeout: 5s
